"""messages table

Revision ID: 6c545acf599e
Revises: 69465dde730c
Create Date: 2023-04-13 23:50:25.324252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c545acf599e'
down_revision = '69465dde730c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversationId', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.String(length=36), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('isUser', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'conversationId', 'userId'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
